export enum ErrorCode {
  DATA_NOT_FOUND = "DATA_NOT_FOUND",
  INVALID_DATE_RANGE = "INVALID_DATE_RANGE",
  INVALID_FUND = "INVALID_FUND",
  NAV_DATA_UNAVAILABLE = "NAV_DATA_UNAVAILABLE",
  DATABASE_ERROR = "DATABASE_ERROR",
  AGENT_ERROR = "AGENT_ERROR",
  VALIDATION_ERROR = "VALIDATION_ERROR",
  INTERNAL_ERROR = "INTERNAL_ERROR"
}
